### ISSUE TITLE
go get 报错

### ISSUE THREAD

**Issue by rjguanwen** [henrylee2cn/erpc#74]
go get -u -f github.com/henrylee2cn/erpc
# github.com/henrylee2cn/erpc/quic
github.com\henrylee2cn\erpc\quic\quic.go:27:36: not enough arguments in call to sess.OpenStreamSync
        have ()
        want (context.Context)
github.com\henrylee2cn\erpc\quic\quic.go:96:27: not enough arguments in call to l.lis.Accept
        have ()
        want (context.Context)
github.com\henrylee2cn\erpc\quic\quic.go:100:34: not enough arguments in call to sess.AcceptStream
        have ()
        want (context.Context)

**Comment by henrylee2cn** [comment]
`rm -rf $GOPATH/src/github.com/henrylee2cn/erpc && GO111MODULE=on go get  github.com/henrylee2cn/erpc`

**Comment by rjguanwen** [comment]
Thinks !

**Comment by rjguanwen** [comment]
Thanks!
