### ISSUE TITLE
quic调用的github.com/lucas-clemente/quic-go库升级了

### ISSUE THREAD

**Issue by C4o** [henrylee2cn/erpc#75]
https://github.com/lucas-clemente/quic-go/commit/2b8cece60ae996a2a34ba9eab7d1c37860cef66d#diff-7fa3e81a10e876cd5bdc7f4b7f4909b0

OpenStreamSync多了参数
类似的还有erpc/quic/quic.go下的96和100行

**Comment by henrylee2cn** [comment]
Make sure you use go mod
