### ISSUE TITLE
使用govendor后的报错

### ISSUE THREAD

**Issue by C4o** [henrylee2cn/erpc#76]
不使用govendor的话正常，但是使用了govendor会有一些的报错，老哥能帮忙看看嘛。。

vendor/github.com/henrylee2cn/erpc/plugin/auth/auth.go:111:21: cannot use sess (type erpc.PreSession) as type Session in argument to a.bearerFunc:
        erpc.PreSession does not implement Session (wrong type for Swap method)
                have Swap() "github.com/henrylee2cn/goutil".Map
                want Swap() "rock/agent/vendor/github.com/henrylee2cn/goutil".Map

vendor/github.com/henrylee2cn/erpc/context.go:375:20: cannot use statCodeMtypeNotAllowed (type *"rock/agent/vendor/github.com/henrylee2cn/goutil/status".Status) as type *"github.com/henrylee2cn/goutil/status".Status in argument to c.output.SetStatus

**Comment by henrylee2cn** [comment]
Make sure all dependencies are in the current vendor

**Comment by C4o** [comment]
govendor同步好像自动同步的是erpc/v6路径，所以我导入的才会自动到gopath下去找，已解决。
