### ISSUE TITLE
c++ client 

### ISSUE THREAD

**Issue by sleepreading** [henrylee2cn/erpc#79]
可以使用C++客户端连接erpc的服务吗.  这种情况下, erpc服务使用哪种协议比较方便客户端组包或解包? pb、raw?
有没有可能erpc服务自定义数据包的格式. 比如 |len|version|body-bytes-data...|
这样客户端可以比较方便的与服务端做数据交互,而且也提供了自定义协议的能力.

**Comment by henrylee2cn** [comment]
是可以自定义协议，可以参考已经实现的那几个协议

**Comment by sleepreading** [comment]
谢谢, 确实看到了如何自定义协议!
我个人然觉得: proto目录里面的的默认实现还是很容易与codec里面的默认实现造成混淆:
**proto即协议本身, 它的其职责仅应该是**: 定义每个数据包的格式, 比如前几个字节表示什么意思, 如前4B表示长度,后面这个长度的数据都算作是**真实有效数据**, 而这些数据如何解析, 是codec的事情(或者是动态的:依据协议扩展字段xferpip)
**codec的职责很简单**: 正如其名,定义真实数据的具体编码格式,仅此而已.
所以我所说的混淆就是(现举一例), proto里面有一个jsonproto的默认实现,实际上该协议的数据部分可以是json编码也可以是其他, 但默认绑定了codec/json_codec.
我觉得proto目录涉及到协议的部分可以与codec目录不强相关. 这样比较容易理解.
事实上_/proto/pbproto_的协议格式与_/proto/jsonproto_类似,可以看做是同一类型的协议,区别仅仅是真实数据的编解码格式不同.
真正协议上有区别的,我感觉应该是http、raw、(上面的)、thrift(不了解数据包格式)
不知道我的理解对不对

**Comment by henrylee2cn** [comment]
你的理解没问题。proto和codec其实是不同层次的。不过proto的格式封包解包过程也是可以用json之类的格式。所以，两者有有可能被混淆

leiz <notifications@github.com> 于 2019年12月29日 周日 23:41写道：
