### ISSUE TITLE
GOARCH=arm 编译失败,存在类型不匹配问题

### ISSUE THREAD

**Issue by om0nster** [henrylee2cn/erpc#84]
/gopathdir/pkg/mod/github.com/henrylee2cn/ameda@v1.3.4/int.go:174:26: constant 4294967295 overflows int
/gopathdir/pkg/mod/github.com/henrylee2cn/ameda@v1.3.4/uint.go:66:8: constant 9223372036854775807 overflows uint
/gopathdir/pkg/mod/github.com/henrylee2cn/ameda@v1.3.4/uint.go:127:7: constant 9223372036854775807 overflows uint
Makefile:28: recipe for target 'server_pi' failed

**Comment by om0nster** [comment]
GOOS=linux GOARCH=arm go build -ldflags "-s -w" -o bin/pi/server server.go
go version go1.14 linux/amd64

**Comment by henrylee2cn** [comment]
我这里没有arm机器，麻烦告诉我，具体是erpc的哪里？

**Comment by henrylee2cn** [comment]
是不是32位系统？为什么我按照你的命令执行，没有报错呢？

**Comment by henrylee2cn** [comment]
直接导致原因是：你可能升级过goutil版本，因为erpc指定版本是没问题的。
根本原因是：最新 goutil 依赖的 ameda 不兼容 32位系统，目前已经修复。
https://github.com/henrylee2cn/erpc/commit/1b8bb0fe4f736b2ed589a09b15794f9a02e13832

**Comment by om0nster** [comment]
更新版本6.3.2,出现新的编译错误.

go 1.14

require (
	github.com/astaxie/beego v1.12.1
	github.com/denisbrodbeck/machineid v1.0.1
	github.com/go-sql-driver/mysql v1.5.0
	github.com/gogo/protobuf v1.3.1 // indirect
	github.com/golang/protobuf v1.4.0
	github.com/henrylee2cn/erpc/v6 v6.3.2
	github.com/klauspost/cpuid v1.2.3 // indirect
	github.com/klauspost/reedsolomon v1.9.3
	github.com/lucas-clemente/quic-go v0.15.3 // indirect
	github.com/shiena/ansicolor v0.0.0-20151119151921-a422bbe96644 // indirect
	golang.org/x/crypto v0.0.0-20200414173820-0848c9571904 // indirect
	golang.org/x/net v0.0.0-20200324143707-d3edc9973b7e
	golang.org/x/sys v0.0.0-20200413165638-669c56c373c4 // indirect
	golang.org/x/text v0.3.2 // indirect
	gopkg.in/check.v1 v1.0.0-20180628173108-788fd7840127 // indirect
	gopkg.in/yaml.v2 v2.2.8 // indirect
)

gopathdir/pkg/mod/github.com/henrylee2cn/erpc/v6@v6.3.2/quic/quic.go:153:9: c.sess.Close undefined (type quic.Session has no field or method Close)
//gopathdir/pkg/mod/github.com/henrylee2cn/erpc/v6@v6.3.2/quic/quic.go:156:15: c.sess.Close undefined (type quic.Session has no field or method Close)
