### ISSUE TITLE
6.3.2版本编译失败

### ISSUE THREAD

**Issue by om0nster** [henrylee2cn/erpc#85]
#84 谢谢快速修订该问题.但是好像新版本存在其他问题

更新版本6.3.2,出现新的编译错误.

go 1.14

require (
github.com/astaxie/beego v1.12.1
github.com/denisbrodbeck/machineid v1.0.1
github.com/go-sql-driver/mysql v1.5.0
github.com/gogo/protobuf v1.3.1 // indirect
github.com/golang/protobuf v1.4.0
github.com/henrylee2cn/erpc/v6 v6.3.2
github.com/klauspost/cpuid v1.2.3 // indirect
github.com/klauspost/reedsolomon v1.9.3
github.com/lucas-clemente/quic-go v0.15.3 // indirect
github.com/shiena/ansicolor v0.0.0-20151119151921-a422bbe96644 // indirect
golang.org/x/crypto v0.0.0-20200414173820-0848c9571904 // indirect
golang.org/x/net v0.0.0-20200324143707-d3edc9973b7e
golang.org/x/sys v0.0.0-20200413165638-669c56c373c4 // indirect
golang.org/x/text v0.3.2 // indirect
gopkg.in/check.v1 v1.0.0-20180628173108-788fd7840127 // indirect
gopkg.in/yaml.v2 v2.2.8 // indirect
)

gopathdir/pkg/mod/github.com/henrylee2cn/erpc/v6@v6.3.2/quic/quic.go:153:9: c.sess.Close undefined (type quic.Session has no field or method Close)
//gopathdir/pkg/mod/github.com/henrylee2cn/erpc/v6@v6.3.2/quic/quic.go:156:15: c.sess.Close undefined (type quic.Session has no field or method Close)

GOOS=linux GOARCH=arm go build -ldflags "-s -w" -o bin/pi/server server.go

**Comment by henrylee2cn** [comment]
你不应该自己指定 github.com/lucas-clemente/quic-go v0.15.3 版本，erpc依赖的是低版本

**Comment by om0nster** [comment]
是的更新后，go mod tidy，清楚无用依赖就可以了。谢谢
