### ISSUE TITLE
被攻击了...崩溃了..

### ISSUE THREAD

**Issue by okwendell** [henrylee2cn/erpc#91]
开始其他人被攻击了，程序直接崩溃了..
后来看了下没有设置包文的大小，传输过来申请内存直接崩溃了，
后来设置了16MB最大报文,还是崩溃.
发现代码应该是有问题，应该是len可能读取到的小于4，导致申请内存出错，crash了.

崩溃堆栈:
goroutine 87366 [running]:
runtime.systemstack_switch()
        /usr/local/Cellar/go@1.14/1.14.10/libexec/src/runtime/asm_amd64.s:330 fp=0xc00021ab78 sp=0xc00021ab70 pc=0x465c50
runtime.mallocgc(0xfffffffc, 0x119d700, 0x1, 0xc00054e370)
        /usr/local/Cellar/go@1.14/1.14.10/libexec/src/runtime/malloc.go:1046 +0x895 fp=0xc00021ac18 sp=0xc00021ab78 pc=0x40cd15
runtime.makeslice(0x119d700, 0xfffffffc, 0xfffffffc, 0x0)
        /usr/local/Cellar/go@1.14/1.14.10/libexec/src/runtime/slice.go:49 +0x6c fp=0xc00021ac48 sp=0xc00021ac18 pc=0x44cd7c
github.com/henrylee2cn/erpc/v6/utils.(*ByteBuffer).ChangeLen(...)
        /Users/wangzhilong/goProject/pkg/mod/github.com/henrylee2cn/erpc/v6@v6.3.4/utils/bytebuffer.go:115
github.com/henrylee2cn/erpc/v6/socket.(*rawProto).readMessage(0xc00024c580, 0xc0000da820, 0x16fab00, 0xc000900a80, 0x0, 0x0)
        /Users/wangzhilong/goProject/pkg/mod/github.com/henrylee2cn/erpc/v6@v6.3.4/socket/protocol.go:237 +0x411 fp=0xc00021acc8 sp=0xc00021ac48 pc=0xce7711
github.com/henrylee2cn/erpc/v6/socket.(*rawProto).Unpack(0xc00024c580, 0x16fab00, 0xc000900a80, 0x0, 0x0)
        /Users/wangzhilong/goProject/pkg/mod/github.com/henrylee2cn/erpc/v6@v6.3.4/socket/protocol.go:204 +0x9a fp=0xc00021ad50 sp=0xc00021acc8 pc=0xce710a
github.com/henrylee2cn/erpc/v6/socket.(*socket).ReadMessage(0xc0002aa960, 0x16fab00, 0xc000900a80, 0x0, 0x0)
        /Users/wangzhilong/goProject/pkg/mod/github.com/henrylee2cn/erpc/v6@v6.3.4/socket/socket.go:236 +0x73 fp=0xc00021ad98 sp=0xc00021ad50 pc=0xce8533
github.com/henrylee2cn/erpc/v6.(*session).startReadAndHandle(0xc000732300)
        /Users/wangzhilong/goProject/pkg/mod/github.com/henrylee2cn/erpc/v6@v6.3.4/session.go:874 +0x26f fp=0xc00021ae40 sp=0xc00021ad98 pc=0xe1adcf
github.com/henrylee2cn/erpc/v6.(*peer).serveListener.func1()
        /Users/wangzhilong/goProject/pkg/mod/github.com/henrylee2cn/erpc/v6@v6.3.4/peer.go:374 +0x2f8 fp=0xc00021af58 sp=0xc00021ae40 pc=0xe1f698
github.com/henrylee2cn/goutil/pool.(*GoPool).goroutineFunc(0xc00037a770, 0xc0002d6220)
        /Users/wangzhilong/goProject/pkg/mod/github.com/henrylee2cn/goutil@v0.0.0-20200416032639-974f5b4094a2/pool/go_pool.go:265 +0x71 fp=0xc00021af98 sp=0xc00021af58 pc=0xdfbbc1
github.com/henrylee2cn/goutil/pool.(*GoPool).getCh.func1(0xc00037a770, 0xc0002d6220, 0x115a940, 0xc0002d6220)
        /Users/wangzhilong/goProject/pkg/mod/github.com/henrylee2cn/goutil@v0.0.0-20200416032639-974f5b4094a2/pool/go_pool.go:241 +0x35 fp=0xc00021afc0 sp=0xc00021af98 pc=0xdfbd75
runtime.goexit()

**Comment by okwendell** [comment]
请确认 修复下..

**Comment by henrylee2cn** [comment]
@okwendell fixed https://github.com/henrylee2cn/erpc/commit/87ff9fa50cbd581a0f54223bb95575db70c27cbb
